[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "https://smartpro.solutions/api/:splat"
status = 200
force = true

[build]
publish = "./dist"
command = "yarn build"