// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    Clock: typeof import('./components/Clock.vue')['default']
    Dancer: typeof import('./components/Dancer.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    Gallery: typeof import('./components/Gallery.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Ico: typeof import('./components/Ico.vue')['default']
    ImagesView: typeof import('./components/ImagesView.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    Paginator: typeof import('./components/Paginator.vue')['default']
    PipSearch: typeof import('./components/PipSearch.vue')['default']
    Placeholder: typeof import('./components/Placeholder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    Streamer: typeof import('./components/Streamer.vue')['default']
    Term: typeof import('./components/Term.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    Todo: typeof import('./components/Todo.vue')['default']
    Uploader: typeof import('./components/Uploader.vue')['default']
    VideosView: typeof import('./components/VideosView.vue')['default']
    Wallpaper: typeof import('./components/Wallpaper.vue')['default']
  }
}
